### ISSUE TITLE
originOS同步失败

### ISSUE THREAD

**Issue by SY-LG** [dujiajun/CourseBlock#7]
# 问题描述

登录后同步课表失败

# 设备信息

- 手机型号：IQOO Neo8 Pro
- 内核版本：5.15.74-android13-8-gd59b17b0ef13-dirty
- 操作系统：OriginOS 3

# 同步信息

- 交课表：v3.2.0
- 设置：本科生，2023-2024，第一学期，2023-09-11---2024-01-14

**Comment by dujiajun** [comment]
v3.2.1 已修复
